/*
Question: What skills are required for the top paying data analyst job?
- Use the top 10 highest-paying Data Analyst jobs from the first query.....
- Add the specific skills required for these roles....
- Why? It provides a detailed look at which high-paying jobs demand certain skills,
    helping job seekers understand which skills to develop that allign with top salaries..........
*/

WITH top_paying_job_skills AS(
    SELECT 
        cd.name AS company_name, -- cd.name is also fine
        jpf.job_posted_date::date AS date_job_posted,
        job_id,
        job_title
        job_location,
        job_schedule_type,
        job_health_insurance,
        salary_year_avg,
        --TO_CHAR(ROUND(salary_year_avg, 0),'FM999,999,999') AS formatted_salary, -- '999,999,999' ensures the number has thousands separators. FM (Fill Mode) removes leading spaces.
        RANK() OVER (ORDER BY salary_year_avg DESC) AS salary_rank,
        CASE
            WHEN jpf.job_location = 'Anywhere' THEN 'Remote'
            ELSE 'Onsite'
        END AS location_category,
        CASE
            WHEN salary_year_avg > 600000 THEN 'Premium'
            WHEN salary_year_avg BETWEEN 400000 AND 600000 THEN 'High'
            WHEN salary_year_avg BETWEEN 200000 AND 400000 THEN 'Mid High'
            WHEN salary_year_avg BETWEEN 100000 AND 200000 THEN 'Mid'
            ELSE 'Low'
        END AS salary_quote
    FROM
        job_postings_fact AS jpf
    LEFT JOIN
        company_dim AS cd ON jpf.company_id = cd.company_id
    WHERE
        job_title_short = 'Data Analyst' AND
        job_location = 'Anywhere' AND
        job_health_insurance IS TRUE AND
        salary_year_avg IS NOT NULL
    ORDER BY
        salary_year_avg DESC
    LIMIT  
        10
)
SELECT
top_paying_job_skills.*,
skills
FROM 
    top_paying_job_skills
INNER JOIN 
    skills_job_dim AS sjd ON top_paying_job_skills.job_id = sjd.job_id
INNER JOIN 
    skills_dim AS sd ON sjd.skill_id = sd.skill_id;


[
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "sql"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "python"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "r"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "azure"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "databricks"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "aws"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "pandas"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "pyspark"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "jupyter"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "excel"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "tableau"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "power bi"
  },
  {
    "company_name": "AT&T",
    "date_job_posted": "2023-06-18",
    "job_id": 552322,
    "job_location": "Associate Director- Data Insights",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "255829.5",
    "salary_rank": "1",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "powerpoint"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "sql"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "python"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "go"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "snowflake"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "pandas"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "numpy"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "excel"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "tableau"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-08-09",
    "job_id": 168310,
    "job_location": "Principal Data Analyst (Remote)",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "205000.0",
    "salary_rank": "2",
    "location_category": "Remote",
    "salary_quote": "Mid High",
    "skills": "gitlab"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sql"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "python"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "go"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "snowflake"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "pandas"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "numpy"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "excel"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "tableau"
  },
  {
    "company_name": "SmartAsset",
    "date_job_posted": "2023-07-11",
    "job_id": 1749593,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "186000.0",
    "salary_rank": "3",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "gitlab"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-06-09",
    "job_id": 387860,
    "job_location": "ERM Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "184000.0",
    "salary_rank": "4",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sql"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-06-09",
    "job_id": 387860,
    "job_location": "ERM Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "184000.0",
    "salary_rank": "4",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "python"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-06-09",
    "job_id": 387860,
    "job_location": "ERM Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "184000.0",
    "salary_rank": "4",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "r"
  },
  {
    "company_name": "Robert Half",
    "date_job_posted": "2023-10-06",
    "job_id": 1781684,
    "job_location": "DTCC Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "170000.0",
    "salary_rank": "5",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "java"
  },
  {
    "company_name": "Robert Half",
    "date_job_posted": "2023-10-06",
    "job_id": 1781684,
    "job_location": "DTCC Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "170000.0",
    "salary_rank": "5",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "go"
  },
  {
    "company_name": "Robert Half",
    "date_job_posted": "2023-10-06",
    "job_id": 1781684,
    "job_location": "DTCC Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "170000.0",
    "salary_rank": "5",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "excel"
  },
  {
    "company_name": "Uber",
    "date_job_posted": "2023-04-18",
    "job_id": 1525451,
    "job_location": "Manager, Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "167000.0",
    "salary_rank": "6",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sql"
  },
  {
    "company_name": "Uber",
    "date_job_posted": "2023-04-18",
    "job_id": 1525451,
    "job_location": "Manager, Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "167000.0",
    "salary_rank": "6",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "python"
  },
  {
    "company_name": "Uber",
    "date_job_posted": "2023-04-18",
    "job_id": 1525451,
    "job_location": "Manager, Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "167000.0",
    "salary_rank": "6",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "r"
  },
  {
    "company_name": "Uber",
    "date_job_posted": "2023-04-18",
    "job_id": 1525451,
    "job_location": "Manager, Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "167000.0",
    "salary_rank": "6",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "swift"
  },
  {
    "company_name": "Uber",
    "date_job_posted": "2023-04-18",
    "job_id": 1525451,
    "job_location": "Manager, Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "167000.0",
    "salary_rank": "6",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "excel"
  },
  {
    "company_name": "Uber",
    "date_job_posted": "2023-04-18",
    "job_id": 1525451,
    "job_location": "Manager, Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "167000.0",
    "salary_rank": "6",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "tableau"
  },
  {
    "company_name": "Uber",
    "date_job_posted": "2023-04-18",
    "job_id": 1525451,
    "job_location": "Manager, Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "167000.0",
    "salary_rank": "6",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "looker"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sql"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "python"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "r"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sas"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "matlab"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "pandas"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "tableau"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "looker"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-08-14",
    "job_id": 712473,
    "job_location": "Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "165000.0",
    "salary_rank": "7",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sas"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sql"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "python"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "scala"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "r"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "mysql"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "postgresql"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "couchbase"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "azure"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "databricks"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "aws"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "redshift"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "oracle"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "snowflake"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "watson"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "pyspark"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "airflow"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "linux"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "tableau"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "ssis"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "cognos"
  },
  {
    "company_name": "DIRECTV",
    "date_job_posted": "2023-06-14",
    "job_id": 918213,
    "job_location": "Senior - Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160515.0",
    "salary_rank": "9",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "visio"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sql"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "python"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "r"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sas"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sql server"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "azure"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "power bi"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "sas"
  },
  {
    "company_name": "Get It Recruit - Information Technology",
    "date_job_posted": "2023-10-13",
    "job_id": 182813,
    "job_location": "Principal Data Analyst",
    "job_schedule_type": "Full-time",
    "job_health_insurance": true,
    "salary_year_avg": "160000.0",
    "salary_rank": "10",
    "location_category": "Remote",
    "salary_quote": "Mid",
    "skills": "ssrs"
  }
]

